### ISSUE TITLE
`rustup .. stable` in rust images

### ISSUE THREAD

**Issue by lsm5** [containers/automation_images#150]
Move the `rustup install/default stable` commands from netavark https://github.com/containers/netavark/pull/338 to the image builds here.

**Comment by cevich** [comment]
More specifically, [move this code into](https://github.com/containers/netavark/pull/338/files#diff-db575befc56ec85f83b824430b9b62e20eb19d08b351dc743db26848639896a6R81-R89) `cache_images/fedora-netavark_packaging.sh`
