### ISSUE TITLE
Add passt (pasta) package for podman

### ISSUE THREAD

**Issue by Luap99** [containers/automation_images#232]
see https://github.com/containers/podman/pull/16141
We should test this in upstream CI.

For fedora it can be installed from the updates-testing repo or this copr (https://copr.fedorainfracloud.org/coprs/sbrivio/passt/)
For ubuntu we could use the deb from here: https://passt.top/builds/latest/x86_64/ (untested)

**Comment by sbrivio-rh** [comment]
> It should also make its way into Debian unstable relatively soon

It's now in [`NEW`](https://ftp-master.debian.org/#new) state for unstable: https://ftp-master.debian.org/new/passt_0.0~git20221104.e308018-1.html.

**Comment by sbrivio-rh** [comment]
> > It should also make its way into Debian unstable relatively soon
> 
> It's now in [`NEW`](https://ftp-master.debian.org/#new) state for unstable: https://ftp-master.debian.org/new/passt_0.0~git20221104.e308018-1.html.

Now accepted for unstable and in `incoming`: http://incoming.debian.org/debian-buildd/pool/main/p/passt/ -- I'll file a Ubuntu sync ticket as soon as the package reaches the pool (which should happen in a few hours).

**Comment by cevich** [comment]
I can add this package to the F37 podman VM no problem.  The Debian SID package should come in handy in a bit.  The Ubuntu -> Debian switch is still in planning.

**Comment by sbrivio-rh** [comment]
> The Debian SID package should come in handy in a bit. The Ubuntu -> Debian switch is still in planning.

Yes yes, I mentioned it just because it needs to be in Debian before we can have it on Ubuntu. I didn't file the sync request for Ubuntu yet as I had some authentication troubles with Launchpad, I'll try again in a bit.
