### ISSUE TITLE
add wireguard-tools package for netavark and Podman

### ISSUE THREAD

**Issue by Luap99** [containers/automation_images#234]
PR https://github.com/containers/netavark/pull/472 adds a wireguard driver, the tests require `wg` to validate the config.

If this is merged we may want to a test in podman as well so that podman images also need that package installed.

**Comment by cevich** [comment]
Okay, so just the wireguard-tools package?  That's easy enough to do.

**Comment by Luap99** [comment]
yeah it may be differently called on ubuntu?
The wireguard driver itself should be already in the kernel since v5.6 as module, you may want to double check with `modinfo wireguard`

**Comment by cevich** [comment]
Ubuntu in CI is being deprecated, so I'm just updating the netavark/aardvark CI VM Images.  Can do podman ones too if required.
