### ISSUE TITLE
add bind-utils to the VM images

### ISSUE THREAD

**Issue by Luap99** [containers/automation_images#336]
I was debugging some dns problems and had to install bind-utils in order to get dig/nslookup. It would be handy if it were installed by default.
According to dnf `Installed size: 5.7 M` so the size should not be that big of a deal to have it by default IMO.
It is not strictly required for tests at the moment but I think it could be at some point when we have to debug dns issues.

**Comment by cevich** [comment]
Should this go into both Fedora and Debian?  Is it okay if it only goes into the VM images and not the Fedora container image?

**Comment by Luap99** [comment]
> Should this go into both Fedora and Debian?

Yes if I have to debug debian specific issue  I would need it there.
But anyhow  it is not really important as I can always install by hand if it needed so I am fine closing this one as no tests depend on it.

**Comment by cevich** [comment]
okay I'll close then.  I also won't argue if you reconsider and want to add the package in the future.
